Repository wp-media/wp-rocket, pull requests merged in 2018-04, with the labels that each got.

#929 Fix #927 add back the SSL cache option
  assets/css/wpr-admin.css
  inc/admin/options.php
  inc/admin/upgrader.php
  inc/classes/admin/settings/class-page.php
  inc/classes/admin/settings/class-render.php
  inc/classes/admin/settings/class-settings.php
  inc/functions/files.php
  src/scss/components/_fieldsContainer.scss
  src/scss/components/_optionHeader.scss
  views/settings/sections/fields-container.php
Labels: enhancement, minor

#932 Fixes #920 Rollback not working on old PHP/WP version
  inc/classes/class-wp-rocket-requirements-check.php
Labels: bug, minor

#933 Fixes #921 PHP Notice for automatic_cleanup_frequency option
  inc/classes/admin/settings/class-settings.php
Labels: bug, minor

#931 Fixes #923 display all options when JS conflict arises
  assets/css/wpr-admin.css
  src/scss/layout/_Page.scss
Labels: bug, minor

#936 Update translations
  languages/rocket-cs_CZ.mo
  languages/rocket-cs_CZ.po
  languages/rocket-de_DE.mo
  languages/rocket-de_DE.po
  languages/rocket-es_ES.mo
  languages/rocket-es_ES.po
  languages/rocket-fr_FR.mo
  languages/rocket-fr_FR.po
  languages/rocket-it_IT.mo
  languages/rocket-it_IT.po
  languages/rocket-ru_RU.mo
  languages/rocket-ru_RU.po
  languages/rocket-tr_TR.mo
  languages/rocket-tr_TR.po
  languages/rocket-zh_CN.mo
  languages/rocket-zh_CN.po
  languages/rocket-zh_TW.mo
  languages/rocket-zh_TW.po
  languages/rocket.pot
Labels: i18n

#937 3.0.3
  assets/css/wpr-admin.css
  inc/admin/options.php
  inc/admin/upgrader.php
  inc/classes/admin/settings/class-page.php
  inc/classes/admin/settings/class-render.php
  inc/classes/admin/settings/class-settings.php
  inc/classes/class-wp-rocket-requirements-check.php
  inc/functions/files.php
  languages/rocket-cs_CZ.mo
  languages/rocket-cs_CZ.po
  languages/rocket-de_DE.mo
  languages/rocket-de_DE.po
  languages/rocket-es_ES.mo
  languages/rocket-es_ES.po
  languages/rocket-fr_FR.mo
  languages/rocket-fr_FR.po
  languages/rocket-it_IT.mo
  languages/rocket-it_IT.po
  languages/rocket-ru_RU.mo
  languages/rocket-ru_RU.po
  languages/rocket-tr_TR.mo
  languages/rocket-tr_TR.po
  languages/rocket-zh_CN.mo
  languages/rocket-zh_CN.po
  languages/rocket-zh_TW.mo
  languages/rocket-zh_TW.po
  languages/rocket.pot
  package-lock.json
  package.json
  src/scss/components/_fieldsContainer.scss
  src/scss/components/_optionHeader.scss
  src/scss/layout/_Page.scss
  views/settings/sections/fields-container.php
  wp-rocket.php
Labels: minor

#951 Fix #945 Prevent DB optimization items count from running on all admin pages
  inc/classes/admin/settings/class-page.php
Labels: bug, major

#954 Fixes #941 Re-add placeholders for fields that had them before 3.0
  inc/classes/admin/settings/class-page.php
  inc/classes/admin/settings/class-render.php
  views/settings/fields/textarea.php
Labels: enhancement, minor

#953 Fixes #915 & #787
  inc/functions/files.php
  inc/functions/minify.php
Labels: enhancement, minor

#956 Fix #943 - Added SumoMe compatibility
  inc/3rd-party/3rd-party.php
  inc/3rd-party/plugins/sumome.php
Labels: 3rd party, bug, minor

#957 Closes #944 - Updated Async CSS to Optimize CSS Delivery
  inc/admin/ui/meta-boxes.php
  inc/classes/admin/settings/class-page.php
Labels: enhancement, minor

#958 Fixes #947 improve Kinsta compatibility
  inc/3rd-party/hosting/kinsta.php
Labels: 3rd party, bug, enhancement, minor

#959 Closes #925 - Force WP Rocket caching on SG Optimizer version below 4.0.5
  inc/3rd-party/hosting/siteground.php
Labels: 3rd party, minor

#966 3.0.4
  inc/3rd-party/3rd-party.php
  inc/3rd-party/hosting/kinsta.php
  inc/3rd-party/hosting/siteground.php
  inc/3rd-party/plugins/sumome.php
  inc/admin/ui/meta-boxes.php
  inc/classes/admin/settings/class-page.php
  inc/classes/admin/settings/class-render.php
  inc/classes/class-rocket-background-database-optimization.php
  inc/classes/class-rocket-database-optimization.php
  inc/front/js/lazyload-10.5.2.js
  inc/front/js/lazyload-10.5.2.min.js
  inc/front/js/lazyload-8.7.1.js
  inc/front/js/lazyload-8.7.1.min.js
  inc/front/lazyload.php
  inc/functions/files.php
  inc/functions/minify.php
  languages/rocket-cs_CZ.mo
  languages/rocket-cs_CZ.po
  languages/rocket-de_DE.mo
  languages/rocket-de_DE.po
  languages/rocket-es_ES.mo
  languages/rocket-es_ES.po
  languages/rocket-fr_FR.mo
  languages/rocket-fr_FR.po
  languages/rocket-it_IT.mo
  languages/rocket-it_IT.po
  languages/rocket-ru_RU.mo
  languages/rocket-ru_RU.po
  languages/rocket-tr_TR.mo
  languages/rocket-tr_TR.po
  languages/rocket-zh_TW.mo
  languages/rocket-zh_TW.po
  languages/rocket.pot
  views/settings/fields/textarea.php
  wp-rocket.php
Labels: minor
