Repository wp-media/wp-rocket, pull requests merged in 2018-11, with the labels that each got.

#1299 Update translations for 3.2
  languages/rocket-es_ES.mo
  languages/rocket-es_ES.po
  languages/rocket-fr_CA.mo
  languages/rocket-fr_CA.po
  languages/rocket-fr_FR.mo
  languages/rocket-fr_FR.po
  languages/rocket-it_IT.mo
  languages/rocket-it_IT.po
  languages/rocket-ro_RO.mo
  languages/rocket-ro_RO.po
  languages/rocket-ru_RU.mo
  languages/rocket-ru_RU.po
  languages/rocket-tr_TR.mo
  languages/rocket-tr_TR.po
  languages/rocket-zh_CN.mo
  languages/rocket-zh_CN.po
  languages/rocket.pot
Labels: i18n

#1309 Improve cache detection from speed tools with a mandatory cookie
  inc/front/process.php
Labels: Module: cache, Type: enhancement

#1311 Fix #762 by sending Expires and Cache-Control headers
  inc/front/process.php
Labels: Module: browser cache, Type: enhancement

#1313 Fixes #1088 Remove Mandatory cookies on hosting with server side cache
  inc/3rd-party/hosting/flywheel.php
  inc/3rd-party/hosting/godaddy.php
  inc/3rd-party/hosting/kinsta.php
  inc/3rd-party/hosting/o2switch.php
  inc/3rd-party/hosting/pressidium.php
  inc/3rd-party/hosting/savvii.php
  inc/3rd-party/hosting/siteground.php
  inc/3rd-party/hosting/wp-serveur.php
  inc/3rd-party/hosting/wpengine.php
  inc/admin/upgrader.php
Labels: Module: cache, Type: enhancement

#1312 Closes #1301 send current theme with a support request from beacon
  inc/classes/admin/settings/class-beacon.php
Labels: Module: dashboard, Type: enhancement

#1319 Improve partial preload
  inc/classes/subscriber/preload/class-partial-preload-subscriber.php
Labels: Module: preload, Type: enhancement

#1321 Homepage preload fix
  inc/classes/preload/class-homepage.php
  inc/functions/formatting.php
Labels: Module: preload, Type: enhancement, community

#1342 Fixes #1332 Ignore cn-reloaded query string
  inc/front/process.php
Labels: 3rd party, Module: cache, Type: enhancement

#1340 Fixes #1331 Correctly display The SEO Framework Sitemap field
  inc/3rd-party/plugins/seo/the-seo-framework.php
Labels: 3rd party, Module: preload, Severity: minor, Type: bug

#1341 Fixes #1334 #1335 Move inline JS after combined JS file
  inc/classes/optimization/JS/class-combine.php
Labels: Module: file optimization, Type: enhancement

#1343 Fixes #1338: Too many requests to clear Sucuri cache on post update
  inc/classes/subscriber/third-party/plugins/security/class-sucuri-subscriber.php
  inc/functions/files.php
Labels: 3rd party, Severity: major, Type: bug

#1339 Correctly check for https cache version during preload
  inc/classes/preload/class-full-process.php
  inc/classes/preload/class-homepage.php
Labels: Module: preload, Type: bug

#1348 Fixes #1336 check for HTTP_USER_AGENT to prevent undefined index
  inc/front/process.php
Labels: Module: cache, Type: bug

#1347 Fixes #1337 Handle array parameters in URL
  inc/front/process.php
Labels: Module: cache, Type: enhancement

#1384 Add documentation for the Cloudflare Add-on
  inc/classes/admin/settings/class-beacon.php
Labels: Module: cloudflare, Severity: minor, Type: bug
