Repository wp-media/wp-rocket, pull requests merged in 2018-02, with the labels that each got.

#752 new Options classes
  inc/classes/admin/class-abstract-options.php
  inc/classes/admin/class-options-data.php
  inc/classes/admin/class-options.php
  inc/functions/options.php
Labels: enhancement, major

#758 Options_Data class update
  inc/classes/admin/class-options-data.php
  inc/functions/options.php
Labels: enhancement, major

#761 Introduce a rendering system
  inc/admin/class-repeater-field.php
  inc/classes/admin/settings/class-render.php
  inc/classes/class-abstract-render.php
  inc/classes/interfaces/class-render-interface.php
Labels: enhancement, major

#776 Closes #772 - Exclude PDF From gzip
  inc/functions/htaccess.php
Labels: enhancement, minor

#777 Fix #775 - Critical Path CSS Not Loaded For Custom Taxonomy Archive Page
  inc/classes/class-rocket-critical-css.php
Labels: bug, minor

#778 Closes #756 - Enhancement - Bring Back LazyLoad on WPtouch
  inc/3rd-party/3rd-party.php
  inc/3rd-party/plugins/mobile/wp-touch.php
Labels: enhancement, minor

#780 Fix #779 - Rewrite rules not written to .htaccess if sub-option is le…
  inc/functions/options.php
Labels: bug, minor

#781 Fix #771 - rocket_get_home_path() breaks cache file generation
  inc/functions/formatting.php
Labels: bug, minor

#773 Fixes #530: Not clearing cache for new posts when using XML-RPC
  inc/front/cdn.php
  wp-rocket.php
Labels: bug, minor

#759 Require autoloader only if it exists.
  wp-rocket.php
Labels: enhancement, minor

#784 Fix #783 - Homepage is not cached if WPS Hide Login's login url is empty
  inc/3rd-party/plugins/security/wps-hide-login.php
Labels: bug, minor
