Repository wp-media/wp-rocket, pull requests merged in 2018-05, with the labels that each got.

#976 WooCommerce compatibility optimization
  inc/3rd-party/3rd-party.php
  inc/3rd-party/plugins/ecommerce/woocommerce.php
  inc/classes/class-plugin.php
  inc/classes/third-party/plugins/ecommerce/class-wc-factory.php
  inc/classes/third-party/plugins/ecommerce/class-woocommerce-compatibility.php
  inc/deprecated.php
Labels: major, new feature

#988 Fix #981 - Space after X-CF-Powered-By: WP Rocket
  inc/common/cloudflare.php
Labels: bug, trivial

#989 Fix #980 - Added arguments for sitemap process request
  inc/functions/bots.php
Labels: bug, minor

#996 Fixes #968 - Prevent cache clear when new image is uploaded to a draft
  inc/common/purge.php
Labels: bug, minor

#990 Fix #986 prevent display of Tools tab and menu when license is not validated
  inc/classes/admin/settings/class-page.php
  views/settings/page.php
Labels: bug, minor

#991 Closes #940 replace domain field by zone ID field in Cloudflare section
  inc/admin/admin.php
  inc/admin/options.php
  inc/admin/upgrader.php
  inc/classes/admin/settings/class-page.php
  inc/classes/admin/settings/class-settings.php
Labels: enhancement, minor

#992 Fix #755 correctly minify relative URLs
  inc/functions/formatting.php
Labels: bug, minor

#998 Add Google Tracking Cache add-on
  assets/img/logo-google-analytics.svg
  composer.json
  composer.lock
  inc/admin/upgrader.php
  inc/classes/admin/settings/class-page.php
  inc/classes/busting/class-abstract-busting.php
  inc/classes/busting/class-busting-factory.php
  inc/classes/busting/class-google-analytics.php
  inc/classes/busting/class-google-tag-manager.php
  inc/classes/class-plugin.php
  inc/classes/subscriber/class-google-tracking-cache-busting-subscriber.php
Labels: major, new feature

#1000 Closes #997 Add a show sidebar switcher
  assets/css/wpr-admin.css
  assets/js/wpr-admin.js
  assets/js/wpr-admin.js.map
  assets/js/wpr-modal.js
  inc/admin/ui/enqueue.php
  src/js/global/main.js
  src/js/global/pageManager.js
  src/scss/layout/_Content.scss
  views/settings/page.php
Labels: enhancement, minor

#994 Fix #993 correctly rewrite referenced file paths in CSS files
  inc/functions/files.php
  inc/functions/minify.php
Labels: bug, minor

#1005 Closes #985: update UI to improve readability and contrast
  assets/css/wpr-admin.css
  assets/img/bg-activated.svg
  assets/img/picto-wprocket-dark.svg
  src/scss/abstracts/_variables.scss
  src/scss/base/_base.scss
  src/scss/components/_field.scss
  src/scss/components/_infoAction.scss
  src/scss/components/_menuItem.scss
  src/scss/components/_notice.scss
  src/scss/components/fields/_checkbox.scss
  src/scss/components/fields/_multiple.scss
  src/scss/components/fields/_textarea.scss
  src/scss/layout/_Content.scss
  src/scss/layout/_Header.scss
  views/settings/page.php
Labels: design, enhancement

#1003 Fix/892 polylang language detection compatibility
  inc/3rd-party/plugins/i18n/polylang.php
  inc/functions/i18n.php
Labels: 3rd party, enhancement, minor
