Repository wp-media/wp-rocket, pull requests merged in 2018-07, with the labels that each got.

#969 Remove Emoji CSS & DNS Prefetch Request
  inc/common/emoji.php
Labels: community, enhancement, minor

#579 Update process.php
  inc/front/process.php
Labels: community, enhancement, minor

#1077 Fix #1070 Prevent DOMDocument bug with closing HTML tags in inline scripts
  inc/classes/class-plugin.php
  inc/classes/optimization/JS/class-combine.php
  inc/classes/subscriber/Optimization/class-combine-google-fonts-subscriber.php
  inc/classes/subscriber/Optimization/class-minify-css-subscriber.php
  inc/classes/subscriber/Optimization/class-minify-html-subscriber.php
  inc/classes/subscriber/Optimization/class-minify-js-subscriber.php
  inc/classes/subscriber/Optimization/class-scripts-escaping-subscriber.php
  inc/classes/traits/trait-config-updater.php
Labels: bug, minor

#1085 o2switch Varnish compatibility
  inc/3rd-party/3rd-party.php
  inc/3rd-party/hosting/o2switch.php
  inc/functions/varnish.php
  inc/main.php
Labels: 3rd party, enhancement, minor

#1084 Remove crawler and use RegEx for HTML parsing
  composer.json
  inc/classes/busting/class-abstract-busting.php
  inc/classes/busting/class-google-analytics.php
  inc/classes/busting/class-google-tag-manager.php
  inc/classes/class-plugin.php
  inc/classes/optimization/CSS/class-abstract-css-optimization.php
  inc/classes/optimization/CSS/class-combine-google-fonts.php
  inc/classes/optimization/CSS/class-combine.php
  inc/classes/optimization/CSS/class-minify.php
  inc/classes/optimization/JS/class-abstract-js-optimization.php
  inc/classes/optimization/JS/class-combine.php
  inc/classes/optimization/JS/class-minify.php
  inc/classes/optimization/class-abstract-optimization.php
  inc/classes/optimization/class-remove-query-string.php
  inc/classes/subscriber/Optimization/class-abstract-minify-subscriber.php
  inc/classes/subscriber/Optimization/class-combine-google-fonts-subscriber.php
  inc/classes/subscriber/Optimization/class-ie-conditionals-subscriber.php
  inc/classes/subscriber/Optimization/class-minify-css-subscriber.php
  inc/classes/subscriber/Optimization/class-minify-js-subscriber.php
  inc/classes/subscriber/Optimization/class-remove-query-string-subscriber.php
  inc/classes/subscriber/Optimization/class-scripts-escaping-subscriber.php
  inc/classes/subscriber/class-google-tracking-cache-busting-subscriber.php
Labels: bug, major
