Repository wp-media/wp-rocket, pull requests merged in 2018-06, with the labels that each got.

#1011 Update WeePie Cookie Allow compatibility
  inc/3rd-party/plugins/cookies/weepie-cookie-allow.php
  inc/front/process.php
Labels: 3rd party, enhancement

#1012 3.0.5
  assets/css/wpr-admin.css
  assets/img/bg-activated.svg
  assets/img/picto-wprocket-dark.svg
  assets/js/wpr-admin.js
  assets/js/wpr-admin.js.map
  assets/js/wpr-modal.js
  composer.lock
  inc/3rd-party/plugins/cookies/weepie-cookie-allow.php
  inc/3rd-party/plugins/i18n/polylang.php
  inc/admin/admin.php
  inc/admin/options.php
  inc/admin/ui/enqueue.php
  inc/admin/upgrader.php
  inc/classes/admin/settings/class-page.php
  inc/classes/admin/settings/class-settings.php
  inc/common/cloudflare.php
  inc/common/purge.php
  inc/front/process.php
  inc/functions/bots.php
  inc/functions/files.php
  inc/functions/formatting.php
  inc/functions/i18n.php
  inc/functions/minify.php
  inc/main.php
  src/js/global/fields.js
  src/js/global/main.js
  src/js/global/pageManager.js
  src/scss/abstracts/_variables.scss
  src/scss/base/_base.scss
  src/scss/components/_field.scss
  src/scss/components/_infoAction.scss
  src/scss/components/_menuItem.scss
  src/scss/components/_notice.scss
  src/scss/components/fields/_checkbox.scss
  src/scss/components/fields/_multiple.scss
  src/scss/components/fields/_textarea.scss
  src/scss/layout/_Content.scss
  src/scss/layout/_Header.scss
  views/settings/fields/cnames.php
  views/settings/page.php
  wp-rocket.php
Labels: minor

#1016 Minify Code Refactor #1: HTML
  composer.lock
  inc/classes/subscriber/Optimization/class-minify-html-subscriber.php
  inc/main.php
Labels: enhancement, minor

#1018 Minify Refactor #2: Combine Google Fonts
  inc/classes/busting/class-google-analytics.php
  inc/classes/optimization/CSS/class-combine-google-fonts.php
  inc/classes/subscriber/Optimization/class-abstract-minify-subscriber.php
  inc/classes/subscriber/Optimization/class-combine-google-fonts-subscriber.php
Labels: enhancement, minor

#1019 Minify Refactor #3: CSS minification/combine
  inc/classes/optimization/CSS/class-abstract-css-optimization.php
  inc/classes/optimization/CSS/class-combine.php
  inc/classes/optimization/CSS/class-minify.php
  inc/classes/optimization/CSS/trait-path-rewriter.php
  inc/classes/optimization/class-abstract-optimization.php
  inc/classes/subscriber/Optimization/class-minify-css-subscriber.php
Labels: enhancement, minor

#1023 Minify Refactor #4: JavaScript
  inc/classes/optimization/JS/class-abstract-js-optimization.php
  inc/classes/optimization/JS/class-combine.php
  inc/classes/optimization/JS/class-minify.php
  inc/classes/subscriber/Optimization/class-minify-js-subscriber.php
Labels: enhancement, major

#1027 Refactor Minify #5: dynamic resources & Remove Query Strings
  inc/classes/optimization/class-cache-dynamic-resource.php
  inc/classes/optimization/class-remove-query-string.php
  inc/classes/subscriber/Optimization/class-cache-dynamic-resource-subscriber.php
  inc/classes/subscriber/Optimization/class-remove-query-string-subscriber.php
Labels: enhancement, minor

#1031 Minify Refactor #6: cleanup
  inc/classes/optimization/CSS/class-combine-google-fonts.php
  inc/classes/optimization/CSS/class-combine.php
  inc/deprecated.php
  inc/front/enqueue.php
  inc/front/minify.php
  inc/functions/minify.php
  inc/functions/options.php
  inc/main.php
Labels: enhancement, minor

#1033 Introduce an event (hook) management system
  inc/3rd-party/plugins/mobile/amp.php
  inc/classes/admin/deactivation/class-deactivation-intent.php
  inc/classes/admin/settings/class-page.php
  inc/classes/class-plugin.php
  inc/classes/event-management/class-event-manager.php
  inc/classes/event-management/event-manager-aware-subscriber-interface.php
  inc/classes/event-management/subscriber-interface.php
  inc/classes/subscriber/Optimization/class-abstract-minify-subscriber.php
  inc/classes/subscriber/Optimization/class-cache-dynamic-resource-subscriber.php
  inc/classes/subscriber/Optimization/class-combine-google-fonts-subscriber.php
  inc/classes/subscriber/Optimization/class-minify-css-subscriber.php
  inc/classes/subscriber/Optimization/class-minify-html-subscriber.php
  inc/classes/subscriber/Optimization/class-minify-js-subscriber.php
  inc/classes/subscriber/Optimization/class-remove-query-string-subscriber.php
  inc/classes/subscriber/class-google-tracking-cache-busting-subscriber.php
  inc/classes/subscriber/third-party/plugins/ecommerce/class-woocommerce-subscriber.php
  inc/classes/traits/trait-config-updater.php
Labels: enhancement, major

#1037 Improve reset OPCache when updating
  inc/admin/upgrader.php
  inc/common/purge.php
  inc/functions/admin.php
Labels: enhancement, minor

#1036 Fix illegal offset type
  inc/functions/i18n.php
Labels: bug, minor

#1040 Fixes #1039 Tell WooCommerce Multilingual that we are caching
  inc/3rd-party/plugins/i18n/wpml.php
Labels: 3rd party, enhancement, minor
