Repository wp-media/wp-rocket, pull requests merged in 2019-11, with the labels that each got.

#2093 Change RegEx for recognizing Firefox version in WebP detection
  inc/classes/Buffer/class-cache.php
Labels: module: media, severity: minor, type: bug

#2090 Fixed #1765 Import Settings on a multisite, fixed mime_type
  inc/admin/admin.php
Labels: Module: dashboard, multisite, severity: minor, type: bug

#2091 Fixed #1904 Clean the archive page of a CPT with SSL
  inc/common/purge.php
Labels: module: cache, severity: minor, type: bug

#2096 Fix #1661 - Detect Jetpack mobile theme
  inc/classes/subscriber/third-party/plugins/class-mobile-subscriber.php
Labels: 3rd party, module: cache, type: enhancement

#2116 Fixes #2095: PHP Warning: date() expects parameter 2 to be int
  inc/classes/admin/settings/class-page.php
Labels: Module: dashboard, severity: trivial, type: bug

#2099 Exclude inline JavaScript keywords - cache directory size
  inc/classes/optimization/JS/class-combine.php
Labels: module: file optimization, type: enhancement

#2117 Closes #2050: Automatic Cache Clearing - Do not attempt to clear cache files when do_rocket_generate_caching_files is false
  inc/classes/Cache/class-expired-cache-purge.php
  tests/Unit/Cache/TestPurgeExpiredFiles.php
Labels: module: cache, severity: minor, type: enhancement

#2133 More reliable licence-data.php deletion
  bin/install-wp-tests.sh
  composer.lock
  inc/admin/upgrader.php
  inc/functions/options.php
  phpcs.xml
  tests/Unit/Addons/Varnish/testPurge.php
  tests/Unit/Admin/Upgrader/testRocketUpgrader.php
  tests/Unit/Functions/Options/TestRocketCheckKey.php
  tests/Unit/Functions/Options/TestRocketDeleteLicenceDataFile.php
  tests/Unit/Subscriber/Addons/VarnishSubscriber/TestCleanDomain.php
  tests/Unit/Subscriber/Addons/VarnishSubscriber/TestCleanFile.php
  tests/Unit/Subscriber/Addons/VarnishSubscriber/TestCleanHome.php
  tests/Unit/Subscriber/Tools/TestDetectMissingTags.php
  tests/Unit/TestCase.php
  tests/Unit/ThirdParty/Plugins/Smush.php
Labels: Module: dashboard, type: enhancement

#2137 Fix #2130 - Cloudflare purge notice displayed on content update
  inc/classes/optimization/JS/class-combine.php
  inc/classes/subscriber/Tools/class-detect-missing-tags-subscriber.php
  inc/functions/cloudflare.php
  tests/Fixtures/Subscriber/Tools/original_both_html_and_body_commented.html
  tests/Fixtures/Subscriber/Tools/original_commented_html_and_body.html
  tests/Fixtures/Subscriber/Tools/original_html_and_body.html
  tests/Fixtures/Subscriber/Tools/original_no_html_and_body.html
  tests/Unit/Subscriber/Tools/TestDetectMissingTags.php
  wp-rocket.php
Labels: module: cloudflare, severity: minor, type: bug
