Repository wp-media/wp-rocket, pull requests merged in 2019-09, with the labels that each got.

#1932 Fix impreza file path
  inc/3rd-party/themes/impreza.php
Labels: 3rd party, module: file optimization, type: enhancement

#1946 Disable webp cache option automatically
  inc/classes/ServiceProvider/class-common-subscribers.php
  inc/classes/subscriber/Media/class-webp-subscriber.php
Labels: type: enhancement

#1950 Added excluded JS
  inc/classes/optimization/JS/class-combine.php
Labels: module: file optimization, type: enhancement

#1951 Native lazyload compatibility
  assets/js/lazyload/12.0/lazyload.js
  assets/js/lazyload/12.0/lazyload.min.js
  assets/js/lazyload/12.0/lazyload.min.js.map
  composer.lock
  inc/classes/subscriber/Optimization/class-lazyload-subscriber.php
Labels: module: lazyload, type: enhancement

#1955 Prevent duplicating cache files without webp
  inc/classes/Buffer/class-cache.php
  inc/classes/subscriber/Media/class-webp-subscriber.php
  inc/functions/files.php
  inc/functions/htaccess.php
Labels: module: cache, type: enhancement

#1953 Unit tests for webp
  inc/classes/subscriber/Media/class-webp-subscriber.php
  tests/Fixtures/Subscriber/Media/WebpSubscriber/html/expected.html
  tests/Fixtures/Subscriber/Media/WebpSubscriber/html/matching.html
  tests/Fixtures/Subscriber/Media/WebpSubscriber/html/not-matching-attributes.html
  tests/Fixtures/Subscriber/Media/WebpSubscriber/html/not-matching-file-extensions.html
  tests/Fixtures/Subscriber/Media/WebpSubscriber/html/not-matching-with-empty-sources.html
  tests/Unit/Subscriber/Media/WebpSubscriber/TestConvertToWebp.php
  tests/Unit/Subscriber/Media/WebpSubscriber/TestMaybeDisableSettingField.php
  tests/Unit/Subscriber/Media/WebpSubscriber/TestMaybeDisableWebpCache.php
  tests/Unit/Subscriber/Media/WebpSubscriber/TestSyncWebpCacheWithThirdPartyPlugins.php
  tests/Unit/Subscriber/Media/WebpSubscriber/TestWebpSectionDescription.php
  tests/Unit/TestCase.php
Labels: module: media, type: enhancement

#1952 Exclude inline JavaScript keywords
  inc/classes/optimization/JS/class-combine.php
Labels: module: file optimization, type: enhancement

#1956 Adapt unit tests for convert_to_webp() to the latest changes
  tests/Fixtures/Subscriber/Media/WebpSubscriber/html/expected.html
  tests/Unit/Subscriber/Media/WebpSubscriber/TestConvertToWebp.php
Labels: module: media, type: bug

#1960 Improved Shortpixel’s webp option sync
  inc/classes/subscriber/third-party/plugins/Images/Webp/class-shortpixel-subscriber.php
Labels: severity: minor, type: bug

#1961 WPR Requirements checks update
  inc/classes/class-wp-rocket-requirements-check.php
  wp-rocket.php
Labels: Module: dashboard, type: bug

#1966 Fix preloader not preloading webp cache
  inc/classes/subscriber/Media/class-webp-subscriber.php
Labels: severity: minor, type: bug

#1969 Prevent fatal error when activating a plugin
  inc/admin/options.php
  inc/functions/htaccess.php
Labels: severity: major, type: bug

#1970 Removed warning about EWWW's ExactDN
  inc/classes/subscriber/third-party/plugins/Images/Webp/class-ewww-subscriber.php
Labels: module: media, type: bug

#1968 Changed texts displayed around the webp cache option
  inc/classes/ServiceProvider/class-common-subscribers.php
  inc/classes/admin/settings/class-page.php
  inc/classes/class-plugin.php
  inc/classes/subscriber/Media/class-webp-subscriber.php
  views/settings/fields/checkbox.php
  views/settings/page-sections/imagify.php
Labels: module: media, type: enhancement

#1971 Adapt unit tests for Webp_Subscriber->webp_section_description() to the latest changes
  inc/classes/subscriber/Media/class-webp-subscriber.php
  tests/Unit/Subscriber/Media/WebpSubscriber/TestConvertToWebp.php
  tests/Unit/Subscriber/Media/WebpSubscriber/TestMaybeDisableSettingField.php
  tests/Unit/Subscriber/Media/WebpSubscriber/TestMaybeDisableWebpCache.php
  tests/Unit/Subscriber/Media/WebpSubscriber/TestSyncWebpCacheWithThirdPartyPlugins.php
  tests/Unit/Subscriber/Media/WebpSubscriber/TestWebpSectionDescription.php
  tests/Unit/TestCase.php
Labels: module: media, type: bug

#1965 Unit tests for class EwwwSubscriber
  tests/Unit/ThirdParty/Plugins/Images/Webp/EwwwSubscriber/TestGetBasename.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/EwwwSubscriber/TestIsConvertingToWebp.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/EwwwSubscriber/TestIsServingWebp.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/EwwwSubscriber/TestIsServingWebpCompatibleWithCdn.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/EwwwSubscriber/TestLoadHooks.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/EwwwSubscriber/TestMaybeAddCdnWarning.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/EwwwSubscriber/TestMaybeRemoveImagesCnames.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/EwwwSubscriber/TestMaybeRemoveImagesFromCdnDropdown.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/WebpCommon/TestPluginActivation.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/WebpCommon/TestPluginDectivation.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/WebpCommon/TestRegister.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/WebpCommon/TestTriggerWebpChange.php
Labels: type: enhancement

#1974 Improved the way to get the "webp header"
  inc/classes/Buffer/class-cache.php
  inc/classes/subscriber/Media/class-webp-subscriber.php
Labels: type: bug

#1973 Preload webp cache after purge
  inc/classes/subscriber/Media/class-webp-subscriber.php
  inc/common/purge.php
Labels: module: preload, type: enhancement

#1975 Capabilities setup
  inc/admin/admin.php
  inc/classes/subscriber/Plugin/class-capabilities-subscriber.php
  inc/main.php
Labels: Module: dashboard, type: enhancement

#1977 Unit tests for class Imagify_Subscriber
  tests/Unit/ThirdParty/Plugins/Images/Webp/EwwwSubscriber/TestIsConvertingToWebp.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/EwwwSubscriber/TestIsServingWebp.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/EwwwSubscriber/TestIsServingWebpCompatibleWithCdn.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/EwwwSubscriber/TestMaybeRemoveImagesFromCdnDropdown.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/ImagifySubscriber/TestGetBasename.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/ImagifySubscriber/TestIsConvertingToWebp.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/ImagifySubscriber/TestIsServingWebp.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/ImagifySubscriber/TestIsServingWebpCompatibleWithCdn.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/ImagifySubscriber/TestLoadHooks.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/ImagifySubscriber/TestSyncOnNetworkOptionAdd.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/ImagifySubscriber/TestSyncOnNetworkOptionDelete.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/ImagifySubscriber/TestSyncOnNetworkOptionUpdate.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/ImagifySubscriber/TestSyncOnOptionAdd.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/ImagifySubscriber/TestSyncOnOptionDelete.php
  tests/Unit/ThirdParty/Plugins/Images/Webp/ImagifySubscriber/TestSyncOnOptionUpdate.php
Labels: module: media, type: new feature

#1978 Exlude inline JavaScript keywords
  inc/classes/optimization/JS/class-combine.php
Labels: module: file optimization, type: enhancement

#1981 Improved wording of the text located under the webp setting in the case the setting is greyd-out
  inc/classes/subscriber/Media/class-webp-subscriber.php
  tests/Unit/Subscriber/Media/WebpSubscriber/TestWebpSectionDescription.php
Labels: module: media, type: enhancement

#1992 Update translations for 3.4
  languages/rocket-es_ES.po
  languages/rocket-fr_FR.po
  languages/rocket-hr.po
  languages/rocket-it_IT.po
  languages/rocket-pl_PL.po
  languages/rocket-pt_BR.po
  languages/rocket-ro_RO.po
  languages/rocket-tr_TR.po
  languages/rocket.pot
Labels: i18n
