Repository wp-media/wp-rocket, pull requests merged in 2024-05, with the labels that each got.

#6600 Fixes #6590 Add LCP/ATF warmup for mobile version
  assets/js/wpr-admin.min.js
  inc/Engine/Media/AboveTheFold/WarmUp/APIClient.php
  inc/Engine/Media/AboveTheFold/WarmUp/Controller.php
  tests/Fixtures/inc/Engine/Media/AboveTheFold/WarmUp/Controller/fetchLinks.php
  tests/Unit/inc/Engine/Media/AboveTheFold/WarmUp/Controller/fetchLinks.php
Labels: type: enhancement, lcp

#6608 Closes #6606 Display notice for 3.16 changes
  inc/Engine/Admin/Beacon/Beacon.php
  inc/Engine/Admin/Settings/Page.php
  inc/Engine/Admin/Settings/Subscriber.php
  inc/admin/upgrader.php
  tests/Fixtures/inc/Engine/Admin/Settings/Page/displayUpdateNotice.php
  tests/Unit/inc/Engine/Admin/Settings/Page/displayUpdateNotice.php
Labels: type: enhancement, module: user interface, lcp

#6611 Closes #6561: Clear critical images should not be in admin bar with invalid license
  inc/Engine/Saas/Admin/AdminBar.php
  tests/Fixtures/inc/Engine/Saas/Admin/AdminBar/addCleanSaasMenuItem.php
  tests/Unit/inc/Engine/Saas/Admin/AdminBar/addCleanSaasMenuItem.php
Labels: type: bug, lcp

#6615 Fixes #6613 Improve LCP warmup process
  inc/Engine/Common/JobManager/APIHandler/APIClient.php
  inc/Engine/Media/AboveTheFold/WarmUp/APIClient.php
  inc/Engine/Media/AboveTheFold/WarmUp/Controller.php
  tests/Fixtures/inc/Engine/Media/AboveTheFold/WarmUp/Controller/fetchLinks.php
  tests/Unit/inc/Engine/Media/AboveTheFold/WarmUp/Controller/fetchLinks.php
Labels: type: enhancement, lcp

#6619 LCP Warmup requests always blocking and default limit to 5
  inc/Engine/Common/JobManager/APIHandler/APIClient.php
  inc/Engine/Media/AboveTheFold/WarmUp/APIClient.php
  inc/Engine/Media/AboveTheFold/WarmUp/Controller.php
  tests/Fixtures/inc/Engine/Media/AboveTheFold/WarmUp/Controller/fetchLinks.php
  tests/Unit/inc/Engine/Media/AboveTheFold/WarmUp/Controller/fetchLinks.php
Labels: type: bug, lcp

#6617 Closes #6541 Add PHPStan CI & level 0 errors
  .github/workflows/lint_phpstan.yml
  composer.json
  inc/Engine/Admin/Database/OptimizationProcess.php
  inc/Engine/Admin/Settings/Page.php
  inc/Engine/CDN/Subscriber.php
  inc/Engine/Cache/AdvancedCache.php
  inc/Engine/Cache/Purge.php
  inc/Engine/Capabilities/Manager.php
  inc/Engine/Common/Queue/Cleaner.php
  inc/Engine/Common/Queue/RUCSSQueueRunner.php
  inc/Engine/CriticalPath/APIClient.php
  inc/Engine/CriticalPath/Admin/Admin.php
  inc/Engine/CriticalPath/ProcessorService.php
  inc/Engine/HealthCheck/ActionSchedulerCheck.php
  inc/Engine/Heartbeat/HeartbeatSubscriber.php
  inc/Engine/Media/ImageDimensions/ImageDimensions.php
  inc/Engine/Media/Lazyload/CSS/Front/MappingFormatter.php
  inc/Engine/Media/Lazyload/CSS/Subscriber.php
  inc/Engine/Optimization/CSSTrait.php
  inc/Engine/Optimization/DeferJS/DeferJS.php
  inc/Engine/Optimization/Minify/AbstractMinifySubscriber.php
  inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php
  inc/Engine/Optimization/RUCSS/Jobs/Manager.php
  inc/Engine/Preload/Controller/LoadInitialSitemap.php
  inc/Engine/Preload/Controller/PreloadUrl.php
  inc/Engine/Preload/Links/Subscriber.php
  inc/ThirdParty/Hostings/Godaddy.php
  inc/ThirdParty/Hostings/Pressidium.php
  inc/ThirdParty/Hostings/Savvii.php
  inc/ThirdParty/Hostings/WPEngine.php
  inc/ThirdParty/Plugins/CDN/CloudflareFacade.php
  inc/ThirdParty/Plugins/ContactForm7.php
  inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php
  inc/ThirdParty/Plugins/I18n/TranslatePress.php
  inc/ThirdParty/Plugins/Optimization/Hummingbird.php
  inc/ThirdParty/Plugins/SEO/AllInOneSEOPack.php
  inc/ThirdParty/Plugins/SEO/RankMathSEO.php
  inc/ThirdParty/Plugins/SEO/SEOPress.php
  inc/ThirdParty/Plugins/SEO/TheSEOFramework.php
  inc/ThirdParty/Plugins/Security/WordFenceCompatibility.php
  inc/ThirdParty/Themes/Themify.php
  phpstan.neon.dist
  tests/phpstan/bootstrap.php
Labels: dev initiative

#6622 Unit tests cleanup
  tests/Fixtures/inc/Engine/License/API/User/isLicenseExpiredGracePeriod.php
  tests/Integration/inc/Engine/Preload/Subscriber/excludePrivatePostUri.php
  tests/Unit/inc/Engine/Common/JobManager/Strategy/Context/RetryContext/setStrategy.php
  tests/Unit/inc/Engine/License/API/User/isLicenseExpiredGracePeriod.php
  tests/Unit/inc/Engine/Preload/Database/Queries/Cache/getOutdatedInProgressJobs.php
  tests/Unit/inc/Engine/Preload/Database/Queries/Cache/makeStatusComplete.php
  tests/Unit/inc/Engine/Preload/Subscriber/excludePrivatePostUri.php
  tests/Unit/inc/ThirdParty/Themes/Divi/addDiviToDescription.php
  tests/Unit/inc/ThirdParty/Themes/Divi/disableDiviJqueryBody.php
  tests/Unit/inc/ThirdParty/Themes/Divi/disableImageDimensionsHeightPercentage.php
  tests/Unit/inc/ThirdParty/Themes/Divi/removeAssetsGenerated.php
  tests/Unit/inc/common/rocketGetPurgeUrls.php
Labels: dev initiative

#6651 Closes #6589: LCP/ATF Warm up process not blocked on local env
  inc/Engine/Media/AboveTheFold/WarmUp/Controller.php
  tests/Fixtures/inc/Engine/Media/AboveTheFold/WarmUp/Subscriber/warmUp.php
  tests/Integration/inc/Engine/Media/AboveTheFold/WarmUp/Subscriber/warmUp.php
Labels: type: enhancement

#6641 Update actions/checkout and actions/cache to v4
  .github/workflows/deploy_dynamic_lists_fallback.yml
  .github/workflows/deploy_plugin.yml
  .github/workflows/licence_data.yml
  .github/workflows/lint_phpcs.yml
  .github/workflows/lint_phpstan.yml
  .github/workflows/test_wprocket.yml
  .github/workflows/test_wprocket_latest_general_coverage.yml
  .github/workflows/test_wprocket_latest_specific.yml
  .github/workflows/test_wprocket_php8.yml
Labels: dev initiative, devops

#6675 Closes #6632: Image Optimization Tab Update
  assets/css/wpr-admin.css
  assets/css/wpr-admin.min.css
  assets/img/imagify-info.svg
  assets/img/imagify-install.svg
  assets/img/imagify-score.png
  inc/Engine/Admin/Settings/Render.php
  src/scss/base/_icons.scss
  src/scss/base/_utilities.scss
  src/scss/components/_imagify.scss
  views/settings/page-sections/imagify.php
Labels: type: enhancement, module: user interface

#6677 Closes #6647: LCP is detected with wrong href coming from a url(xxx) syntax
  assets/js/lcp-beacon.js
  assets/js/lcp-beacon.js.min.map
  assets/js/lcp-beacon.min.js
Labels: type: bug

#6670 Closes #6667: Add header to lcp candidates elements
  inc/Engine/Media/AboveTheFold/Frontend/Controller.php
  tests/Fixtures/inc/Engine/Media/AboveTheFold/Frontend/Subscriber/HTML/output_w_beacon.html
Labels: type: enhancement

#6646 Update delay JS script
  assets/js/lazyload-scripts.min.js
Labels: module: delay JS
