Repository wp-media/wp-rocket, pull requests merged in 2024-02, with the labels that each got.

#6402 Fixes #6276 Prevent running the function `rocket_clean_domain()` multiple times
  inc/functions/files.php
Labels: type: enhancement, module: cache

#6391 Closes #6312: Exclude youtube thumbnail from lazyload
  inc/Dependencies/RocketLazyload/Assets.php
  inc/Engine/Media/Lazyload/Subscriber.php
Labels: type: enhancement, module: lazyload images, module: lazyload iframes and videos, module: lazyload youtube preview image

#6390 Closes #6367 Add theme resolver for compatibility classes
  inc/Plugin.php
  inc/ThirdParty/Themes/Avada.php
  inc/ThirdParty/Themes/Bridge.php
  inc/ThirdParty/Themes/Divi.php
  inc/ThirdParty/Themes/Flatsome.php
  inc/ThirdParty/Themes/Jevelin.php
  inc/ThirdParty/Themes/MinimalistBlogger.php
  inc/ThirdParty/Themes/Polygon.php
  inc/ThirdParty/Themes/ServiceProvider.php
  inc/ThirdParty/Themes/Shoptimizer.php
  inc/ThirdParty/Themes/SubscriberFactory.php
  inc/ThirdParty/Themes/ThemeResolver.php
  inc/ThirdParty/Themes/Themify.php
  inc/ThirdParty/Themes/ThirdpartyTheme.php
  inc/ThirdParty/Themes/Uncode.php
  inc/ThirdParty/Themes/Xstore.php
  tests/Fixtures/inc/ThirdParty/Themes/Divi/addDiviToDescription.php
  tests/Fixtures/inc/ThirdParty/Themes/Divi/maybeDisableYoutubePreview.php
  tests/Integration/inc/ThirdParty/Themes/Avada/TestCase.php
  tests/Integration/inc/ThirdParty/Themes/Avada/cleanDomain.php
  tests/Integration/inc/ThirdParty/Themes/Avada/excludeDeferJs.php
  tests/Integration/inc/ThirdParty/Themes/Avada/excludeDelayJs.php
  tests/Integration/inc/ThirdParty/Themes/Bridge/maybeClearCache.php
  tests/Integration/inc/ThirdParty/Themes/Divi/disableDiviJqueryBody.php
  tests/Integration/inc/ThirdParty/Themes/Divi/disableImageDimensionsHeightPercentage.php
  tests/Integration/inc/ThirdParty/Themes/Divi/handleDiviAdminNotice.php
  tests/Integration/inc/ThirdParty/Themes/Divi/handleSaveTemplate.php
  tests/Integration/inc/ThirdParty/Themes/Divi/maybeDisableYoutubePreview.php
  tests/Integration/inc/ThirdParty/Themes/Divi/removeAssetsGenerated.php
  tests/Integration/inc/ThirdParty/Themes/Flatsome/preservePatterns.php
  tests/Integration/inc/ThirdParty/Themes/Jevelin/preservePatterns.php
  tests/Integration/inc/ThirdParty/Themes/MinimalistBlogger/excludeJqueryFromDelayJs.php
  tests/Integration/inc/ThirdParty/Themes/Shoptimizer/excludeJqueryDeferjsWithCartDrawer.php
  tests/Integration/inc/ThirdParty/Themes/Uncode/excludeDelayJs.php
  tests/Integration/inc/ThirdParty/Themes/Uncode/excludeJs.php
  tests/Integration/inc/ThirdParty/Themes/Xstore/excludeInlineContent.php
  tests/Unit/inc/ThirdParty/Themes/Divi/addDiviToDescription.php
  tests/Unit/inc/ThirdParty/Themes/Divi/maybeDisableYoutubePreview.php
Labels: type: enhancement
