Repository wp-media/wp-rocket, pull requests merged in 2024-11, with the labels that each got.

#7059 Fixes #7042 Argument 2 ($url) passed to exclude_rocket_from_wp_updates() must be of the type string
  inc/Engine/Plugin/UpdaterApiCommonSubscriber.php
  inc/Engine/Plugin/UpdaterSubscriber.php
Labels: type: bug

#7054 Add method to update lists from JSON files and clear cache
  inc/Engine/Optimization/DynamicLists/AbstractDataManager.php
  inc/Engine/Optimization/DynamicLists/DynamicLists.php
  inc/Engine/Optimization/DynamicLists/Subscriber.php
Labels: module: dynamic lists

#7094 Closes #7068 admin UI for host fonts locally
  inc/Engine/Admin/Beacon/Beacon.php
  inc/Engine/Admin/Settings/Page.php
  inc/Engine/Media/Fonts/Admin/Settings.php
  inc/Engine/Media/Fonts/Admin/Subscriber.php
  inc/Engine/Media/Fonts/ServiceProvider.php
  inc/Plugin.php
  tests/Fixtures/inc/admin/rocketFirstInstall.php
  tests/Integration/inc/Engine/Media/ImageDimensions/AdminSubscriber/addOption.php
Labels: module: media, type: sub-task

#7091 Closes #7063: Google font - Frontend part
  inc/Engine/Media/Fonts/Context/Context.php
  inc/Engine/Media/Fonts/Frontend/Controller.php
  inc/Engine/Media/Fonts/Frontend/Subscriber.php
  inc/Engine/Media/Fonts/ServiceProvider.php
  inc/Engine/Optimization/GoogleFonts/Subscriber.php
  inc/Plugin.php
  tests/Fixtures/inc/Engine/Media/Fonts/Context/Context/isAllowed.php
  tests/Fixtures/inc/Engine/Media/Fonts/Frontend/Controller/HTML/expected_v1.php
  tests/Fixtures/inc/Engine/Media/Fonts/Frontend/Controller/HTML/expected_v1_v2.php
  tests/Fixtures/inc/Engine/Media/Fonts/Frontend/Controller/HTML/expected_v2.php
  tests/Fixtures/inc/Engine/Media/Fonts/Frontend/Controller/HTML/input_v1.php
  tests/Fixtures/inc/Engine/Media/Fonts/Frontend/Controller/HTML/input_v1_v2.php
  tests/Fixtures/inc/Engine/Media/Fonts/Frontend/Controller/HTML/input_v2.php
  tests/Fixtures/inc/Engine/Media/Fonts/Frontend/Controller/rewriteFonts.php
  tests/Integration/inc/Engine/Optimization/GoogleFonts/Combine/optimize.php
  tests/Unit/bootstrap.php
  tests/Unit/inc/Engine/Media/Fonts/Context/Context/isAllowed.php
  tests/Unit/inc/Engine/Media/Fonts/Frontend/Controller/rewriteFonts.php
Labels: type: sub-task

#7083 Closes #7062 Fonts filesystem
  inc/Engine/Common/AbstractFileSystem.php
  inc/Engine/Media/Fonts/Filesystem.php
  inc/Engine/Media/Fonts/Frontend/Controller.php
  inc/Engine/Media/Fonts/Frontend/Subscriber.php
  inc/Engine/Media/Fonts/ServiceProvider.php
  inc/Engine/Optimization/RUCSS/Controller/Filesystem.php
  inc/Plugin.php
  tests/Fixtures/inc/Engine/Media/Fonts/Filesystem/writeFontCss.php
  tests/Fixtures/inc/Engine/Media/Fonts/Frontend/Controller/HTML/expected_v1.php
  tests/Fixtures/inc/Engine/Media/Fonts/Frontend/Controller/HTML/expected_v1_v2.php
  tests/Fixtures/inc/Engine/Media/Fonts/Frontend/Controller/HTML/expected_v2.php
  tests/Fixtures/inc/Engine/Media/Fonts/Frontend/Controller/rewriteFonts.php
  tests/Unit/inc/Engine/Media/Fonts/Filesystem/writeFontCss.php
  tests/Unit/inc/Engine/Media/Fonts/Frontend/Controller/rewriteFonts.php
Labels: type: sub-task

#7107 Closes #7065: 3.18 - Filter changing output
  inc/Engine/Common/AbstractFileSystem.php
  inc/Engine/Media/Fonts/Frontend/Controller.php
  tests/Fixtures/inc/Engine/Media/Fonts/Frontend/Subscriber/HTML/expected_v1.php
  tests/Fixtures/inc/Engine/Media/Fonts/Frontend/Subscriber/HTML/expected_v1_style_tag.php
  tests/Fixtures/inc/Engine/Media/Fonts/Frontend/Subscriber/HTML/expected_v1_v2.php
  tests/Fixtures/inc/Engine/Media/Fonts/Frontend/Subscriber/HTML/expected_v2.php
  tests/Fixtures/inc/Engine/Media/Fonts/Frontend/Subscriber/HTML/input_v1.php
  tests/Fixtures/inc/Engine/Media/Fonts/Frontend/Subscriber/HTML/input_v1_v2.php
  tests/Fixtures/inc/Engine/Media/Fonts/Frontend/Subscriber/HTML/input_v2.php
  tests/Fixtures/inc/Engine/Media/Fonts/Frontend/Subscriber/rewriteFonts.php
  tests/Integration/inc/Engine/Media/Fonts/Frontend/Subscriber/rewriteFonts.php
Labels: type: enhancement

#7117 Release v3.17.3
  assets/js/wpr-admin.js
  assets/js/wpr-admin.min.js
  assets/js/wpr-admin.min.js.map
  dynamic-lists-delayjs.json
  dynamic-lists.json
  inc/Engine/Admin/Beacon/Beacon.php
  inc/Engine/Admin/Database/Optimization.php
  inc/Engine/Admin/Settings/Page.php
  inc/Engine/CDN/RocketCDN/DataManagerSubscriber.php
  inc/Engine/CDN/RocketCDN/NoticesSubscriber.php
  inc/Engine/CDN/RocketCDN/ServiceProvider.php
  inc/Engine/Cache/TaxonomySubscriber.php
  inc/Engine/HealthCheck/HealthCheck.php
  inc/Engine/Optimization/DynamicLists/AbstractDataManager.php
  inc/Engine/Optimization/DynamicLists/DynamicLists.php
  inc/Engine/Optimization/DynamicLists/ServiceProvider.php
  inc/Engine/Optimization/DynamicLists/Subscriber.php
  inc/Engine/Plugin/UpdaterApiCommonSubscriber.php
  inc/Engine/Plugin/UpdaterSubscriber.php
  inc/Engine/WPRocketUninstall.php
  inc/functions/admin.php
  languages/rocket-fa_IR.mo
  languages/rocket-fa_IR.po
  languages/rocket-fr_FR.mo
  languages/rocket-fr_FR.po
  languages/rocket.pot
  licence-data.php
  src/js/global/ajax.js
  tests/Fixtures/inc/Engine/Cache/TaxonomySubscriber/disableCacheOnNotValidTaxonomyPages.php
  tests/Integration/inc/Engine/Optimization/DynamicLists/Subscriber/addDynamicListsScript.php
  tests/Unit/inc/Engine/Optimization/DynamicLists/Subscriber/addDynamicListsScript.php
  views/settings/page-sections/tutorials.php
  wp-rocket.php
Labels: release-alpha

#7121 Closes #7120: PHPStan - Discourage apply_filters in Favor of wpm_apply_filters_typed()
  composer.json
  phpstan-baseline.neon
  phpstan.neon.dist
  tests/phpstan/Rules/DiscourageApplyFilters.php
Labels: type: enhancement, noQA

#7134 Fixes #7133 Correctly load translations in some cases + remaining doing_it_wrong warning
  inc/Engine/Common/JobManager/APIHandler/AbstractSafeAPIClient.php
  wp-rocket.php
Labels: type: bug, i18n

#7124 Closes #7123: Rules about get_subscribed_events
  composer.json
  phpstan.neon.dist
  tests/phpstan/Rules/EnsureCallbackMethodsExistsInSubscribedEvents.php
  tests/phpstan/tests/Rules/EnsureCallbackMethodsExistsInSubscribedEventsTest.php
  tests/phpstan/tests/bootstrap.php
  tests/phpstan/tests/data/EnsureCallbackMethodsExistsInSubscribedEventsTest/complex-syntax.php
  tests/phpstan/tests/data/EnsureCallbackMethodsExistsInSubscribedEventsTest/not-existing.php
  tests/phpstan/tests/data/EnsureCallbackMethodsExistsInSubscribedEventsTest/valid.php
  tests/phpstan/tests/phpunit.xml
Labels: type: enhancement, noQA

#7139 Closes #7136: Discourage use of update_option()
  phpstan-baseline.neon
  phpstan.neon.dist
  tests/phpstan/Rules/DiscourageUpdateOptionUsage.php
  tests/phpstan/tests/Rules/DiscourageUpdateOptionUsageTest.php
  tests/phpstan/tests/data/DiscourageUpdateOptionUsageTest/not-valid.php
  tests/phpstan/tests/data/DiscourageUpdateOptionUsageTest/valid.php
  tests/phpstan/tests/phpunit.xml
Labels: type: enhancement, noQA
