Repository wp-media/wp-rocket, pull requests merged in 2024-07, with the labels that each got.

#6427 Preload adaptative batch
  inc/Engine/Preload/Controller/PreloadUrl.php
  inc/Engine/WPRocketUninstall.php
  tests/Fixtures/inc/Engine/Preload/Controller/PreloadUrl/preloadUrl.php
  tests/Fixtures/inc/Engine/Preload/Controller/PreloadUrl/processPendingJobs.php
  tests/Fixtures/inc/Engine/Preload/Cron/Subscriber/processPendingUrls.php
  tests/Integration/inc/Engine/WPRocketUninstall/uninstall.php
  tests/Unit/inc/Engine/Preload/Controller/PreloadUrl/preloadUrl.php
  tests/Unit/inc/Engine/Preload/Controller/PreloadUrl/processPendingJobs.php
Labels: type: enhancement, module: preload

#6754 Closes #6621 Increase phpstan level to level 1
  inc/Engine/CDN/RocketCDN/AdminPageSubscriber.php
  inc/Engine/CDN/RocketCDN/views/cta-big.php
  inc/Engine/CDN/RocketCDN/views/cta-small.php
  inc/Engine/CDN/RocketCDN/views/dashboard-status.php
  inc/Engine/Common/Database/Queries/AbstractQuery.php
  inc/Engine/Common/Database/Tables/AbstractTable.php
  inc/Engine/CriticalPath/APIClient.php
  inc/Engine/License/views/promo-banner.php
  inc/Engine/License/views/renewal-expired-banner-ocd-disabled.php
  inc/Engine/License/views/renewal-expired-banner-ocd.php
  inc/Engine/License/views/renewal-expired-banner.php
  inc/Engine/License/views/renewal-soon-banner.php
  inc/Engine/License/views/upgrade-popin.php
  inc/Engine/Media/AboveTheFold/Database/Queries/AboveTheFold.php
  inc/Engine/Media/AboveTheFold/Frontend/Controller.php
  inc/Engine/Media/ImageDimensions/ImageDimensions.php
  inc/Engine/Optimization/CSSTrait.php
  inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php
  inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php
  inc/Engine/Optimization/UrlTrait.php
  inc/Engine/Preload/Controller/PreloadUrl.php
  inc/Engine/Preload/Database/Queries/Cache.php
  inc/ThirdParty/Plugins/Optimization/AMP.php
  phpstan.neon.dist
  tests/Fixtures/inc/ThirdParty/Hostings/LiteSpeed/override_header_functions.php
  tests/Fixtures/inc/ThirdParty/Plugins/SEO/SEOPress/fixtures.php
  tests/Integration/inc/Engine/CriticalPath/CriticalCSSSubscriber/deleteCpcss.php
  tests/Integration/inc/Engine/CriticalPath/ProcessorService/processGenerate.php
  tests/Integration/inc/Engine/Media/ImageDimensions/Subscriber/specifyImageDimensions.php
  tests/Integration/inc/Engine/Optimization/DelayJS/Subscriber/delayJs.php
  tests/Integration/inc/Engine/Optimization/RUCSS/Frontend/Subscriber/maybeDisablePreloadFonts.php
  tests/Unit/inc/Engine/Cache/Purge/purgePostTermsUrls.php
  tests/Unit/inc/Engine/Common/JobManager/Strategy/Strategies/JobSetFail/execute.php
  tests/Unit/inc/Engine/CriticalPath/Admin/Admin/enqueueAdminCpcssHeartbeatScript.php
  tests/Unit/inc/ThirdParty/Plugins/Optimization/AMP/disableOptionsOnAmp.php
  tests/Unit/inc/functions/rocketRrmdir.php
  tests/phpstan/phpstan-bootstrap.php
Labels: type: enhancement, dev initiative

#6723 Overwrite .htaccess file after deleting rules even if there is no content
  inc/functions/htaccess.php
Labels: priority: low

#6706 Added support for WooCommerce Multilingual Standalone Version
  inc/3rd-party/plugins/ecommerce/woocommerce-multilingual.php
Labels: priority: low

#6783 Closes #4966 Remove warnings on minify CSS/JS options
  inc/Engine/Admin/Settings/Page.php
Labels: module: minify CSS, module: minify JS, module: user interface

#6785 Fixes #6758 Use array_filter to remove empty values from excluded values
  inc/Dependencies/RocketLazyload/Image.php
  inc/Engine/Media/Lazyload/CSS/Subscriber.php
Labels: type: bug, module: lazyload images, module: lazyload background css images

#6782 Fix typos
  assets/css/wpr-admin.css
  assets/js/wpr-admin.js
  inc/3rd-party/hosting/presslabs.php
  inc/3rd-party/plugins/seo/premium-seo-pack.php
  inc/3rd-party/plugins/sumome.php
  inc/Addon/Cloudflare/Subscriber.php
  inc/Addon/WebP/Subscriber.php
  inc/Dependencies/Minify/CSS.php
  inc/Dependencies/Monolog/Utils.php
  inc/Dependencies/RocketLazyload/Image.php
  inc/Engine/CDN/CDN.php
  inc/Engine/Cache/AdminSubscriber.php
  inc/Engine/Cache/PurgeExpired/PurgeExpiredCache.php
  inc/Engine/Common/Queue/AbstractASQueue.php
  inc/Engine/Common/Queue/QueueInterface.php
  inc/Engine/Common/Queue/RUCSSQueueRunner.php
  inc/Engine/Media/ImageDimensions/ImageDimensions.php
  inc/Engine/Media/ImageDimensions/Subscriber.php
  inc/Engine/Optimization/RUCSS/Jobs/Factory.php
  inc/Engine/Preload/Database/Queries/Cache.php
  inc/Engine/Support/Data.php
  inc/Logger/Logger.php
  inc/Plugin.php
  inc/ThirdParty/Plugins/CDN/CloudflareFacade.php
  inc/admin/admin.php
  inc/admin/options.php
  inc/classes/Buffer/class-tests.php
  inc/classes/subscriber/third-party/plugins/Images/Webp/class-ewww-subscriber.php
  inc/deprecated/3.3.php
  inc/deprecated/3.6.php
  inc/deprecated/3.8.php
  inc/deprecated/Engine/Addon/GoogleTracking/GoogleAnalytics.php
  inc/deprecated/Engine/Addon/GoogleTracking/Subscriber.php
  inc/deprecated/classes/busting/class-facebook-pickles.php
  inc/deprecated/classes/busting/class-facebook-sdk.php
  inc/deprecated/deprecated.php
  inc/functions/files.php
  inc/functions/htaccess.php
  inc/functions/options.php
  src/js/global/fields.js
  src/scss/main.scss
  tests/Fixtures/inc/Engine/Support/Data/getSupportData.php
  tests/Fixtures/inc/classes/Buffer/Tests/canProcessBuffer.php
  views/settings/fields/hidden.php
Labels: type: bug

#6793 Closes #6721 Move rocket analytics field to my account section
  inc/Engine/Admin/Settings/Page.php
  views/settings/page-sections/dashboard.php
Labels: type: enhancement, Module: dashboard

#6798 Fix risky tests and tests generating PHP warnings
  tests/Fixtures/inc/Engine/Saas/Admin/Notices/displayProcessingNotice.php
  tests/Fixtures/inc/Engine/Saas/Admin/Notices/displaySuccessNotice.php
  tests/Integration/inc/Engine/Admin/Settings/Subscriber/enableSeparateCacheFilesMobile.php
  tests/Integration/inc/Engine/Optimization/Minify/CSS/AdminSubscriber/onUpdate.php
  tests/Integration/inc/Engine/Optimization/RUCSS/Frontend/Subscriber/onUpdate.php
  tests/StubTrait.php
  tests/Unit/inc/Engine/Saas/Admin/Notices/displayProcessingNotice.php
  tests/Unit/inc/Engine/Saas/Admin/Notices/displaySuccessNotice.php
Labels: dev initiative, noQA

#6800 Update badge in README
  README.md
Labels: type: enhancement

#6805 Update API endpoints to new domain
  inc/Engine/Activation/Activation.php
  inc/Engine/CDN/RocketCDN/AdminPageSubscriber.php
  inc/Engine/Deactivation/Deactivation.php
  inc/Engine/License/API/PricingClient.php
  inc/Engine/License/API/UserClient.php
  inc/Engine/Plugin/InformationSubscriber.php
  inc/Engine/Plugin/ServiceProvider.php
  inc/Engine/Plugin/UpdaterApiCommonSubscriber.php
  inc/Engine/Plugin/UpdaterSubscriber.php
  inc/admin/ui/enqueue.php
  inc/classes/class-wp-rocket-requirements-check.php
  inc/functions/options.php
  tests/Fixtures/inc/Engine/CDN/RocketCDN/AdminPageSubscriber/addSubscriptionModal.php
  tests/Fixtures/inc/Engine/License/Renewal/addLocalizeScriptData.php
  tests/Fixtures/inc/Engine/License/Subscriber/addLocalizeScriptData.php
  tests/Fixtures/inc/Engine/License/Upgrade/addLocalizeScriptData.php
  tests/Unit/inc/functions/rocketCheckKey.php
  wp-rocket.php
Labels: type: enhancement

#6794 Closes #6779: AboveTheFold Database Refactor
  assets/js/wpr-beacon.js
  assets/js/wpr-beacon.min.js
  assets/js/wpr-beacon.min.js.map
  inc/Engine/Common/PerformanceHints/Cron/Controller.php
  inc/Engine/Common/PerformanceHints/Cron/Subscriber.php
  inc/Engine/Common/PerformanceHints/Database/Queries/AbstractQueries.php
  inc/Engine/Common/PerformanceHints/Database/Queries/QueriesInterface.php
  inc/Engine/Common/PerformanceHints/Database/Table/AbstractTable.php
  inc/Engine/Common/PerformanceHints/Database/Table/TableInterface.php
  inc/Engine/Common/PerformanceHints/FactoryInterface.php
  inc/Engine/Common/PerformanceHints/Frontend/Processor.php
  inc/Engine/Common/PerformanceHints/ServiceProvider.php
  inc/Engine/Media/AboveTheFold/Admin/Controller.php
  inc/Engine/Media/AboveTheFold/Cron/Controller.php
  inc/Engine/Media/AboveTheFold/Cron/Subscriber.php
  inc/Engine/Media/AboveTheFold/Database/Queries/AboveTheFold.php
  inc/Engine/Media/AboveTheFold/Database/Tables/AboveTheFold.php
  inc/Engine/Media/AboveTheFold/Factory.php
  inc/Engine/Media/AboveTheFold/ServiceProvider.php
  inc/Plugin.php
  package-lock.json
  package.json
  tests/Fixtures/inc/Engine/Common/PerformanceHints/Cron/Controller/scheduleCleanup.php
  tests/Fixtures/inc/Engine/Common/PerformanceHints/Cron/Subscriber/cleanup.php
  tests/Fixtures/inc/Engine/Common/PerformanceHints/Frontend/Subscriber/HTML/output_w_beacon.html
  tests/Integration/inc/Engine/Common/JobManager/Cron/Subscriber/checkJobStatus.php
  tests/Integration/inc/Engine/Common/PerformanceHints/Cron/Controller/scheduleCleanup.php
  tests/Integration/inc/Engine/Common/PerformanceHints/Cron/Subscriber/cleanup.php
  tests/Unit/inc/Engine/Media/AboveTheFold/Admin/Controller/truncateAtf.php
  tests/Unit/inc/Engine/Media/AboveTheFold/Admin/Controller/truncateOnUpdate.php
Labels: effort: [S], module: OCI

#6803 Closes #6799 Increase PHPStan level to 3
  inc/Engine/Admin/API/Subscriber.php
  inc/Engine/Admin/Settings/Page.php
  inc/Engine/Cache/PurgeExpired/PurgeExpiredCache.php
  inc/Engine/Common/Database/Tables/AbstractTable.php
  inc/Engine/Common/JobManager/Queue/Queue.php
  inc/Engine/Common/Queue/AbstractASQueue.php
  inc/Engine/Common/Queue/Cleaner.php
  inc/Engine/Common/Queue/QueueInterface.php
  inc/Engine/Common/Queue/RUCSSQueueRunner.php
  inc/Engine/CriticalPath/Admin/Post.php
  inc/Engine/License/Renewal.php
  inc/Engine/Media/Lazyload/CSS/Admin/Subscriber.php
  inc/Engine/Optimization/CacheDynamicResource.php
  inc/Engine/Optimization/RUCSS/Admin/Subscriber.php
  inc/Engine/Optimization/UrlTrait.php
  inc/Engine/Preload/Controller/Queue.php
  inc/Engine/Preload/Fonts.php
  inc/Engine/Preload/Links/Subscriber.php
  inc/ThirdParty/Plugins/Security/WordFenceCompatibility.php
  inc/ThirdParty/Themes/Avada.php
  inc/ThirdParty/Themes/SubscriberFactory.php
  inc/functions/formatting.php
  phpstan.neon.dist
  tests/Integration/ASTrait.php
  tests/Integration/AjaxTestCase.php
  tests/Unit/inc/Engine/Admin/Settings/Page/asyncWistiaScript.php
  tests/Unit/inc/Engine/Admin/Settings/Page/displayUpdateNotice.php
  tests/Unit/inc/Engine/Admin/Settings/Page/enableMobileCache.php
  tests/Unit/inc/Engine/Admin/Settings/Page/enableSeparateCacheFilesMobile.php
  tests/Unit/inc/Engine/Admin/Settings/Page/enqueueRocketScripts.php
  tests/Unit/inc/Engine/CriticalPath/Admin/Post/cpcssActions.php
  tests/Unit/inc/Engine/CriticalPath/RESTWPPost/delete.php
  tests/Unit/inc/Engine/CriticalPath/RESTWPPost/generate.php
Labels: dev initiative
