Repository wp-media/wp-rocket, pull requests merged in 2024-01, with the labels that each got.

#6335 Fixes #6325 Detect existing fetchpriority attribute when spaces around equal sign
  inc/Engine/Media/AboveTheFold/Frontend/Controller.php
Labels: type: bug, lcp

#6362 Closes #6360: Fix ll bgcss markup
  assets/js/lazyload-css.js
  assets/js/lazyload-css.min.js
  assets/js/lazyload-css.min.js.map
  inc/Engine/Media/Lazyload/CSS/Front/TagGenerator.php
  src/js/global/lazyload-css.js
  tests/Fixtures/inc/Engine/Media/Lazyload/CSS/Front/TagGenerator/generate.php
  tests/Fixtures/inc/Engine/Media/Lazyload/CSS/Subscriber/integration/HTML/html_excluded.php
  tests/Fixtures/inc/Engine/Media/Lazyload/CSS/Subscriber/integration/HTML/html_output.php
Labels: type: bug, priority: high, module: lazyload background css images

#6334 Refactor clean RUCSS/Critical images dashboard button
  inc/Engine/Media/AboveTheFold/Admin/Controller.php
  inc/Engine/Media/AboveTheFold/Admin/Subscriber.php
  inc/Engine/Media/AboveTheFold/Database/Tables/AboveTheFold.php
  inc/Engine/Optimization/RUCSS/Admin/Subscriber.php
  inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php
  inc/Engine/Optimization/RUCSS/ServiceProvider.php
  inc/Engine/Saas/Admin/AdminBar.php
  inc/Engine/Saas/Admin/Clean.php
  inc/Engine/Saas/Admin/Subscriber.php
  inc/Engine/Saas/ServiceProvider.php
  inc/classes/class-abstract-render.php
  views/settings/page-sections/dashboard.php
  views/settings/sections/clean-section.php
Labels: type: enhancement, lcp

#6346 Closes #6310: Update Delayjs to 1.2.5
  assets/js/lazyload-scripts.min.js
  tests/Fixtures/inc/Engine/Optimization/DelayJS/Subscriber/addDelayJsScript.php
Labels: type: enhancement, module: delay JS

#6378 Add ?nowrocket check to disable core lazyload method
  inc/Engine/Media/Lazyload/Subscriber.php
Labels: type: bug, module: lazyload images

#6376 Closes #6343: Fix Webtoffee compatibility
  inc/Engine/Activation/Activation.php
Labels: type: bug, 3rd party compatibility, effort: [XS]

#6318 Closes #6309 Add PHP 8.3 to tests matrix
  .github/workflows/test_wprocket.yml
  .github/workflows/test_wprocket_php8.yml
  composer.json
Labels: dev initiative

#6405 Closes #6401: update delay js script to version 1.2.5.1
  assets/js/lazyload-scripts.min.js
  tests/Fixtures/inc/Engine/Optimization/DelayJS/Subscriber/addDelayJsScript.php
Labels: type: bug, module: delay JS

#6397 Closes #6349: Update renewal banner with discount percentage instead of difference
  inc/Engine/License/Renewal.php
  inc/Engine/License/views/renewal-expired-banner-ocd.php
  tests/Fixtures/inc/Engine/License/Renewal/displayRenewalExpiredBanner.php
  tests/Fixtures/inc/Engine/License/Renewal/displayRenewalSoonBanner.php
  tests/Fixtures/inc/Engine/License/Subscriber/displayRenewalSoonBanner.php
Labels: type: enhancement, Module: dashboard

#6383 Show last 4 digits CloudFlare Add-on
  assets/js/wpr-admin.js.min.map
  assets/js/wpr-admin.min.js
  inc/Engine/Admin/Settings/Page.php
  inc/admin/options.php
  src/js/global/fields.js
Labels: type: enhancement, module: cloudflare, effort: [S]

#6404 Closes #6389: LL for CSS BG Images coming from PHP file
  inc/Engine/Media/Lazyload/CSS/Front/ContentFetcher.php
Labels: priority: medium, effort: [XS], severity: major, module: lazyload background css images

#6386 Closes #4943: Delete transients on plugin uninstallation
  inc/Engine/WPRocketUninstall.php
Labels: type: bug, Module: dashboard

#6409 Closes #6394: Reintroduce limit preload at job level
  inc/Engine/Preload/Database/Queries/Cache.php
  tests/Fixtures/inc/Engine/Preload/Cron/Subscriber/processPendingUrls.php
  tests/Fixtures/inc/Engine/Preload/Database/Queries/Cache/getPendingJobs.php
  tests/Unit/inc/Engine/Preload/Database/Queries/Cache/getPendingJobs.php
Labels: type: enhancement, module: preload
