Repository wp-media/wp-rocket, pull requests merged in 2024-04, with the labels that each got.

#6546 Fixes #6545 error in integration test with WP 6.5
  tests/Fixtures/inc/Engine/Optimization/Minify/JS/Subscriber/process.php
  tests/Integration/inc/Engine/CriticalPath/CriticalCSSSubscriber/deleteCpcss.php
Labels: type: bug, test

#6548 Closes #6518: inject beacon for saas
  inc/Engine/Media/AboveTheFold/Frontend/Controller.php
  inc/Engine/Media/AboveTheFold/Frontend/Subscriber.php
  inc/Engine/Media/ImageDimensions/Subscriber.php
Labels: type: enhancement

#6517 3.16 bug the warm up of lcpatf is not triggered when clicking clear critical images in the admin
  inc/Engine/Media/AboveTheFold/Admin/Controller.php
  inc/Engine/Media/AboveTheFold/Admin/Subscriber.php
  tests/Fixtures/inc/Engine/Media/AboveTheFold/Admin/Controller/truncateAtfAdmin.php
  tests/Integration/inc/Engine/Media/AboveTheFold/Admin/Controller/truncateAtfAdmin.php
Labels: type: bug, lcp

#6585 Updated test data to cover scenario
  tests/Fixtures/inc/Engine/Media/AboveTheFold/WarmUp/Controller/fetchLinks.php
Labels: test

#6565 Fixes #6509 Don't display clear critical images for this URL on admin view
  inc/Engine/Saas/Admin/AdminBar.php
  tests/Fixtures/inc/Engine/Saas/Admin/AdminBar/addCleanSaasMenuItem.php
  tests/Fixtures/inc/Engine/Saas/Admin/AdminBar/addCleanUrlMenuItem.php
  tests/Unit/inc/Engine/Saas/Admin/AdminBar/addCleanSaasMenuItem.php
  tests/Unit/inc/Engine/Saas/Admin/AdminBar/addCleanUrlMenuItem.php
Labels: type: bug, lcp

#6580 Fixes #6576 Add safe guard for links limit filter value in warmup
  inc/Engine/Media/AboveTheFold/WarmUp/Controller.php
Labels: type: bug, lcp

#6592 Closes #6591: LCP/ATF data is malformed when no LCP is found by the beacon
  assets/js/lcp-beacon.js
  assets/js/lcp-beacon.js.min.map
  assets/js/lcp-beacon.min.js
Labels: type: bug, priority: high

#6562 Fix #6526 LCP/ATF messages that is not working correctly
  assets/js/wpr-admin.js
  assets/js/wpr-admin.js.min.map
  assets/js/wpr-admin.min.js
  inc/Engine/Optimization/RUCSS/Admin/Subscriber.php
  inc/Engine/Saas/Admin/Notices.php
  inc/Engine/WPRocketUninstall.php
  src/js/global/countdown.js
  tests/Unit/inc/Engine/Optimization/RUCSS/Admin/Subscriber/cleanUsedCssAndCache.php
  tests/Unit/inc/Engine/Optimization/RUCSS/Admin/Subscriber/maybeSetProcessingTransient.php
  tests/Unit/inc/Engine/Optimization/RUCSS/Admin/Subscriber/truncateUsedCss.php
Labels: type: bug, lcp

#6586 Closes #6575: Should not fetch rss feed or rest api links from homepage
  inc/Engine/Media/AboveTheFold/WarmUp/Controller.php
  tests/Fixtures/inc/Engine/Media/AboveTheFold/WarmUp/Controller/fetchLinks.php
Labels: type: bug, lcp

#6595 Fixes #6574 Display console message only in debug mode
  assets/js/lcp-beacon.js
  assets/js/lcp-beacon.js.min.map
  assets/js/lcp-beacon.min.js
  inc/Engine/Media/AboveTheFold/Frontend/Controller.php
  tests/Fixtures/inc/Engine/CDN/Subscriber/HTML/siteURL/expected.html
  tests/Fixtures/inc/Engine/CDN/Subscriber/HTML/siteURLWithPath/expected.html
  tests/Fixtures/inc/Engine/CDN/Subscriber/rewrite.php
  tests/Fixtures/inc/Engine/Media/AboveTheFold/Frontend/Subscriber/HTML/output_w_beacon.html
  tests/Fixtures/inc/Engine/Optimization/Minify/CSS/Subscriber/process.php
  tests/Fixtures/inc/Engine/Optimization/Minify/JS/Subscriber/process.php
  tests/Fixtures/inc/ThirdParty/Hostings/WPEngine/Int/addFootprint.php
  tests/Fixtures/inc/ThirdParty/Themes/Divi/Integration/disableImageDimensionsHeightPercentage.php
  tests/Fixtures/inc/ThirdParty/Themes/Divi/disableImageDimensionsHeightPercentage.php
  tests/Integration/inc/Engine/CDN/Subscriber/rewrite.php
  tests/Integration/inc/Engine/Optimization/Minify/CSS/Subscriber/process.php
  tests/Integration/inc/Engine/Optimization/Minify/JS/Subscriber/process.php
  tests/Integration/inc/ThirdParty/Hostings/WPEngine/addFootprint.php
  tests/Integration/inc/ThirdParty/Themes/Divi/disableImageDimensionsHeightPercentage.php
Labels: type: enhancement

#6587 Task/6471 remove treeshake param and provide logs of sent requests
  inc/Engine/Common/JobManager/JobProcessor.php
  tests/Fixtures/inc/Engine/Common/JobManager/APIHandler/APIClient/optimize.php
  tests/Fixtures/inc/Engine/Optimization/RUCSS/Controller/UsedCSS/treeshake.php
Labels: lcp

#6013 Closes #5992: Get rid of the cache tab
  assets/img/icon-user-cache.svg
  assets/js/wpr-admin.js
  assets/js/wpr-admin.js.map
  assets/js/wpr-admin.js.min.map
  assets/js/wpr-admin.min.js
  inc/Engine/Admin/Settings/Page.php
  inc/Engine/Admin/Settings/ServiceProvider.php
  inc/Engine/Admin/Settings/Subscriber.php
  inc/Engine/Cache/AdminSubscriber.php
  inc/admin/admin.php
  inc/admin/options.php
  inc/admin/upgrader.php
  inc/functions/htaccess.php
  src/js/global/ajax.js
  tests/Fixtures/DIContainer.php
  tests/Fixtures/inc/Engine/Admin/Settings/Page/enableMobileCache.php
  tests/Fixtures/inc/Engine/Admin/Settings/Page/enableSeparateCacheFilesMobile.php
  tests/Fixtures/inc/Engine/Admin/Settings/Subscriber/enableMobileCache.php
  tests/Fixtures/inc/Engine/Admin/Settings/Subscriber/enableSeparateCacheFilesMobile.php
  tests/Fixtures/inc/admin/rocketFirstInstall.php
  tests/Integration/inc/Engine/Admin/Settings/Subscriber/enableMobileCache.php
  tests/Integration/inc/Engine/Admin/Settings/Subscriber/enableSeparateCacheFilesMobile.php
  tests/Unit/inc/Engine/Admin/Settings/Page/asyncWistiaScript.php
  tests/Unit/inc/Engine/Admin/Settings/Page/enableMobileCache.php
  tests/Unit/inc/Engine/Admin/Settings/Page/enableSeparateCacheFilesMobile.php
  tests/Unit/inc/Engine/Admin/Settings/Page/enqueueRocketScripts.php
  tests/Unit/inc/Engine/Optimization/RUCSS/Controller/UsedCSS/treeshake.php
  views/settings/mobile-cache.php
  wp-rocket.php
Labels: type: enhancement, epics 🔥, module: user interface

#6342 Closes #6329: Deprecate RUCSS Hooks
  assets/js/lcp-beacon.js
  assets/js/lcp-beacon.js.min.map
  assets/js/wpr-admin.js.min.map
  inc/Engine/Activation/Activation.php
  inc/Engine/Common/Database/Queries/AbstractQuery.php
  inc/Engine/Common/Database/Tables/AbstractTable.php
  inc/Engine/Common/JobManager/Cron/Subscriber.php
  inc/Engine/Common/JobManager/JobProcessor.php
  inc/Engine/Common/JobManager/Strategy/Strategies/DefaultProcess.php
  inc/Engine/Common/Utils.php
  inc/Engine/Debug/RUCSS/Subscriber.php
  inc/Engine/Optimization/RUCSS/Admin/Subscriber.php
  inc/Engine/Saas/Admin/Notices.php
  inc/ThirdParty/Plugins/I18n/WPML.php
  inc/functions/admin.php
  tests/Fixtures/inc/functions/admin/rocketDeprecateAction.php
  tests/Fixtures/inc/functions/admin/rocketDeprecateFilter.php
  tests/Integration/inc/functions/admin/rocketDeprecateAction.php
  tests/Integration/inc/functions/admin/rocketDeprecateFilter.php
  tests/Unit/inc/Engine/Common/JobManager/Cron/Subscriber/cronCleanRows.php
  tests/Unit/inc/Engine/Common/JobManager/Strategy/Strategies/DefaultProcess/execute.php
  tests/Unit/inc/Engine/Optimization/RUCSS/Admin/Subscriber/deleteTermUsedCss.php
  tests/Unit/inc/Engine/Optimization/RUCSS/Admin/Subscriber/truncateUsedCss.php
  tests/Unit/inc/Engine/Optimization/RUCSS/Controller/UsedCSS/treeshake.php
Labels: type: sub-task, lcp
